---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/fotnite-vevo/bluefin
name: bluefin
# description will be included in the image's metadata
description: fotnite-vevo's personal Bluefin image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable # latest is also supported if you want new updates ASAP

modules:
  - type: rpm-ostree
    repos:
      - https://download.opensuse.org/repositories/home:/TheLocehiliosan:/yadm/Fedora_%OS_VERSION%/home:TheLocehiliosan:yadm.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
    install:
      - gnome-backgrounds-extras
      - neovim
      - yadm
      - zellij
      - morewaita-icon-theme

    remove:
      - gnome-tour
      - solaar

  - type: yafti

  - type: signing
